apiVersion: intent.security/v1alpha1
kind: ContainerIntent
metadata:
  name: permissive-app
spec:
  egress:
    - ports:
        - number: 22
          protocol: TCP
        - number: 80
          protocol: TCP
        - number: 443
          protocol: TCP
        - number: 8080
          protocol: TCP
        - number: 3000
          protocol: TCP
        - number: 5432
          protocol: TCP
