apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db-service-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: db-service
  policyTypes:
  - Egress
  egress: []
